/**
 * app/legal/terms/page.tsx
 *
 * Plain language Terms of Service for Draftly AI.
 */
import Link from "next/link";
import { DraftlyLogo } from "@/components/ui/icons";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0F] text-[#F4F4FA] selection:bg-[#8B5CF6]/30">
      <header className="border-b border-white/10 bg-[#0A0A0F]/80 backdrop-blur-xl">
        <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2.5 font-display text-lg font-bold text-white">
            <DraftlyLogo className="h-6 w-6" />
            <span>
              Draft<span className="text-[#8B5CF6]">ly</span> Terms
            </span>
          </Link>
          <Link href="/" className="text-xs text-[#8E8EA3] hover:text-white transition">
            ← Back to Home
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="font-display text-3xl font-extrabold text-white mb-2">Terms of Service</h1>
        <p className="text-xs text-[#8E8EA3] font-mono mb-8">Last Updated: August 2026</p>

        <div className="space-y-6 text-sm text-[#8E8EA3] leading-relaxed">
          <section className="glass-panel p-6 border border-white/10 rounded-2xl">
            <h2 className="font-display text-base font-semibold text-white mb-2">1. Overview</h2>
            <p>
              Welcome to Draftly AI. By signing up or using our services, you agree to these clear and honest terms. Draftly provides AI-assisted content generation tools powered by advanced AI models.
            </p>
          </section>

          <section className="glass-panel p-6 border border-white/10 rounded-2xl">
            <h2 className="font-display text-base font-semibold text-white mb-2">2. Credits & Subscriptions</h2>
            <p>
              Draftly uses a credit-based system. Starter accounts receive 15 free credits upon registration. Pro subscriptions grant 500 credits per billing period. Credits are deducted per generation request and tracked transparently in your append-only ledger. You can cancel your subscription at any time via the billing portal.
            </p>
          </section>

          <section className="glass-panel p-6 border border-white/10 rounded-2xl">
            <h2 className="font-display text-base font-semibold text-white mb-2">3. Content Ownership</h2>
            <p>
              You own all rights, title, and interest in the content generated using your prompts on Draftly. We do not claim ownership over any text, captions, or threads generated by your account.
            </p>
          </section>

          <section className="glass-panel p-6 border border-white/10 rounded-2xl">
            <h2 className="font-display text-base font-semibold text-white mb-2">4. Acceptable Use</h2>
            <p>
              You agree not to use Draftly to generate illegal content, hate speech, automated spam campaigns, or material that infringes on third-party intellectual property.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
